services:
  mc:
    image: itzg/minecraft-server:java21
    container_name: mc-create-aeronautics
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      VERSION: "1.21.1"
      NEOFORGE_VERSION: "21.1.227"
      MEMORY: "8G"
      INIT_MEMORY: "2G"
      USE_AIKAR_FLAGS: "true"
      MAX_PLAYERS: "6"
      MOTD: "Create Aeronautics | Industrial Skyworks"
      LEVEL: "world"
      DIFFICULTY: "normal"
      MODE: "survival"
      PVP: "false"
      ALLOW_FLIGHT: "true"
      ENABLE_COMMAND_BLOCK: "false"
      ONLINE_MODE: "false"
      ENFORCE_WHITELIST: "false"
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "8"
      SPAWN_PROTECTION: "0"
      MODRINTH_PROJECTS: "@/extras/server-mods.txt"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_PROJECTS_DEFAULT_VERSION_TYPE: "release"
      REMOVE_OLD_MODS: "true"
      TZ: "Europe/Moscow"
    volumes:
      - ./data:/data
      - ./extras:/extras:ro

  gravitlauncher:
    image: ghcr.io/gravitlauncher/launcher:v5.7.11
    container_name: mc-gravitlauncher
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./gravitlauncher/data:/app/data
    environment:
      TZ: "Europe/Moscow"

  gravitlauncher-nginx:
    image: nginx:stable
    container_name: mc-gravitlauncher-nginx
    restart: unless-stopped
    ports:
      - "7240:80"
    volumes:
      - ./gravitlauncher/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./gravitlauncher/data/updates:/volume:ro
    depends_on:
      - gravitlauncher

  modpack-http:
    image: caddy:2-alpine
    container_name: mc-modpack-http
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./modpack:/usr/share/caddy:ro